In [1]:
!pip install opencv-python

In [1]:
# Import opencv
import cv2 

# Import uuid
import uuid

# Import Operating System
import os

# Import time
import time

In [2]:
labels = ['thumbup', 'thumbdown', 'thankyou', 'livelong']
number_imgs = 5

In [3]:
IMAGES_PATH = os.path.join('workspace', 'images', 'collectedimages')

In [4]:
if not os.path.exists(IMAGES_PATH):
    if os.name == 'posix':
        !mkdir -p {IMAGES_PATH}
    if os.name == 'nt':
         !mkdir {IMAGES_PATH}
for label in labels:
    path = os.path.join(IMAGES_PATH, label)
    if not os.path.exists(path):
        !mkdir {path}

In [8]:
for label in labels:
    cap = cv2.VideoCapture(0)
    cap.set(3, 480)
    cap.set(4, 640)
    print('Collecting images for {}'.format(label))
    time.sleep(5)
    for imgnum in range(number_imgs):
        print('Collecting image {}'.format(imgnum))
        ret, frame = cap.read()
        imgname = os.path.join(IMAGES_PATH,label,label+'.'+'{}.jpg'.format(str(uuid.uuid1())))
        cv2.imwrite(imgname, frame)
        cv2.imshow('frame', frame)
        time.sleep(2)

        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
cap.release()
cv2.destroyAllWindows()

In [6]:
!pip install --upgrade pyqt5 lxml

In [5]:
LABELIMG_PATH = os.path.join('labelimg')

In [8]:
!conda install -c anaconda git

Solving environment: ...working... done

# All requested packages already installed.



In [12]:
if not os.path.exists(LABELIMG_PATH):
    !mkdir {LABELIMG_PATH}
!git clone https://github.com/tzutalin/labelImg {LABELIMG_PATH}

Cloning into 'labelimg'...


In [6]:
if os.name == 'posix':
    !make qt5py3
if os.name =='nt':
    !cd {LABELIMG_PATH} && pyrcc5 -o libs/resources.py resources.qrc

In [14]:
!cd {LABELIMG_PATH} && python labelImg.py

Image:C:\Users\Dell\python\TFOD\workspace\images\collectedimages\livelong\livelong.e8b9c5a7-13b8-11ed-bb8d-c025a5433bea.jpg -> Annotation:C:/Users/Dell/python/TFOD/workspace/images/collectedimages/livelong\livelong.e8b9c5a7-13b8-11ed-bb8d-c025a5433bea.xml
Cancel creation.
Image:C:\Users\Dell\python\TFOD\workspace\images\collectedimages\livelong\livelong.ed914a21-13b8-11ed-8038-c025a5433bea.jpg -> Annotation:C:/Users/Dell/python/TFOD/workspace/images/collectedimages/livelong\livelong.ed914a21-13b8-11ed-8038-c025a5433bea.xml
Image:C:\Users\Dell\python\TFOD\workspace\images\collectedimages\livelong\livelong.e9ee758e-13b8-11ed-8a79-c025a5433bea.jpg -> Annotation:C:/Users/Dell/python/TFOD/workspace/images/collectedimages/livelong\livelong.e9ee758e-13b8-11ed-8a79-c025a5433bea.xml
Image:C:\Users\Dell\python\TFOD\workspace\images\collectedimages\livelong\livelong.eb258772-13b8-11ed-ba67-c025a5433bea.jpg -> Annotation:C:/Users/Dell/python/TFOD/workspace/images/collectedimages/livelong\livelong.

In [8]:
!pip install beautifulsoup4
!pip install lxml

In [9]:
import os
os.getcwd()

'D:\\Programming\\Python\\TFOD'

In [7]:
IMAGES_PATH = os.path.join('workspace', 'images', 'collectedimages')

In [8]:
LIVELONG_PATH = os.path.join(IMAGES_PATH, "livelong")

In [9]:
from bs4 import BeautifulSoup
with open(os.path.join(LIVELONG_PATH, "livelong.e8b9c5a7-13b8-11ed-bb8d-c025a5433bea.xml"), "r") as r:
    data = r.read()

Bs_data = BeautifulSoup(data,"xml")
boundbox = Bs_data.find("bndbox")
bb = boundbox.get_text().split("\n")
bbox = [ele for ele in bb if ele.strip()]
print(bbox, boundbox)

FileNotFoundError: [Errno 2] No such file or directory: 'workspace\\images\\collectedimages\\livelong\\livelong.e8b9c5a7-13b8-11ed-bb8d-c025a5433bea.xml'

In [10]:
import pathlib
image_count = len(list(pathlib.Path(LIVELONG_PATH).glob("*.")))
image_count

0

In [11]:
import glob

for filename in glob.glob(os.path.join(LIVELONG_PATH, "*.xml" )):
    ...

TRAIN_PATH = os.path.join('workspace', 'images', 'train')
TEST_PATH = os.path.join("workspace", 'images', 'test')
for path in [TRAIN_PATH, TEST_PATH]:
    if not os.path.exists(path):
        os.makedirs(path)
        
os.listdir(LIVELONG_PATH)

['livelong.e9ee758e-13b8-11ed-8a79-c025a5433bea.jpg',
 'livelong.e9ee758e-13b8-11ed-8a79-c025a5433bea.xml',
 'livelong.eb258772-13b8-11ed-ba67-c025a5433bea.jpg',
 'livelong.eb258772-13b8-11ed-ba67-c025a5433bea.xml',
 'livelong.ec5b4922-13b8-11ed-88c3-c025a5433bea.jpg',
 'livelong.ec5b4922-13b8-11ed-88c3-c025a5433bea.xml',
 'livelong.ed914a21-13b8-11ed-8038-c025a5433bea.jpg',
 'livelong.ed914a21-13b8-11ed-8038-c025a5433bea.xml']

In [12]:
import shutil

shutil.copy(os.path.join(LIVELONG_PATH,os.listdir(LIVELONG_PATH)[1]), 
            os.path.join(TRAIN_PATH,os.listdir(LIVELONG_PATH)[1]))

'workspace\\images\\train\\livelong.e9ee758e-13b8-11ed-8a79-c025a5433bea.xml'

In [13]:
import numpy as np 

ratio = 0.8

index = np.random.permutation(5)
train_index = index[:int(0.8*5)]
test_index = index[int(0.8*5):]
print(train_index)
print(test_index)

[3 1 0 2]
[4]


In [14]:
def splitSetFromFile(cur_path, target_path, ratio = 0.8):
    index = np.random.permutation(len(list(pathlib.Path(cur_path).glob("*.xml"))))
    if len(index) != 0.5*len(os.listdir(cur_path)):
        print("UNMATCH ERROR in {}".format(cur_path))
    else:
        train_index = index[:int(ratio*len(index))]
        test_index = index[int(ratio*len(index)):]
        # Create Train n Test file
        TRAIN_PATH = os.path.join(target_path, "train")
        TEST_PATH = os.path.join(target_path, "test")
        if not os.path.exists(TRAIN_PATH):
            os.makedirs(TRAIN_PATH)
        if not os.path.exists(TEST_PATH):
            os.makedirs(TEST_PATH)
        
        for i in train_index:
            shutil.copy(os.path.join(cur_path,os.listdir(cur_path)[2*i]), 
                os.path.join(TRAIN_PATH,os.listdir(cur_path)[2*i]))
            shutil.copy(os.path.join(cur_path,os.listdir(cur_path)[2*i + 1]), 
                os.path.join(TRAIN_PATH,os.listdir(cur_path)[2*i + 1])) 
        for i in test_index:
            shutil.copy(os.path.join(cur_path,os.listdir(cur_path)[2*i]), 
                os.path.join(TEST_PATH,os.listdir(cur_path)[2*i]))
            shutil.copy(os.path.join(cur_path,os.listdir(cur_path)[2*i + 1]), 
                os.path.join(TEST_PATH,os.listdir(cur_path)[2*i + 1])) 
        return (TRAIN_PATH, TEST_PATH)

In [15]:
THANKYOU_PATH = os.path.join(IMAGES_PATH, "thankyou")
TARGET_PATH = os.path.join("workspace", "images")
for label in labels:
    PATH = os.path.join(IMAGES_PATH, label)
    splitSetFromFile(PATH, TARGET_PATH, ratio = 0.6)

In [16]:
import tensorflow as tf

BytesList = tf.train.BytesList
FloatList = tf.train.FloatList
Int64List = tf.train.Int64List
Feature = tf.train.Feature
Features = tf.train.Features
Example = tf.train.Example

In [17]:
import cv2
def createExample(image_file, label_file):
    img = cv2.imread(image_file)
    #img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    image_data = tf.io.encode_jpeg(img)
    print(image_data)
    with open(label_file, "r") as f:
        label_data = f.read()
    Bs_data = BeautifulSoup(label_data,"xml")
    bb = Bs_data.find("bndbox").get_text().split("\n")
    boundbox = [int(ele) for ele in bb if ele.strip()]
    label = Bs_data.find("name").get_text()
    return Example(
        features = Features(
            feature = {
                "image" : Feature(bytes_list = BytesList(value = [image_data.numpy()])),
                "label" : Feature(int64_list=Int64List(value=[labels.index(label.lower())])),
                "xmin" : Feature(int64_list=Int64List(value=[boundbox[0]])),
                "ymin" : Feature(int64_list=Int64List(value=[boundbox[1]])),
                "xmax" : Feature(int64_list=Int64List(value=[boundbox[2]])),
                "ymax" : Feature(int64_list=Int64List(value=[boundbox[3]])),
            }
        )
    )

In [21]:
img = cv2.imread(os.path.join(TRAIN_PATH,"livelong.e8b9c5a7-13b8-11ed-bb8d-c025a5433bea.jpg"))
img = cv2.resize(img, (640,480))
cv2.imshow("image", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\resize.cpp:4052: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'


In [18]:
example_with_image = createExample(os.path.join(THANKYOU_PATH, "thankyou.de00e415-13b8-11ed-8cee-c025a5433bea.jpg"),
              os.path.join(THANKYOU_PATH, "thankyou.de00e415-13b8-11ed-8cee-c025a5433bea.xml"))
serialized_example = example_with_image.SerializeToString()

tf.Tensor(b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01\x01,\x01,\x00\x00\xff\xdb\x00C\x00\x02\x01\x01\x01\x01\x01\x02\x01\x01\x01\x02\x02\x02\x02\x02\x04\x03\x02\x02\x02\x02\x05\x04\x04\x03\x04\x06\x05\x06\x06\x06\x05\x06\x06\x06\x07\t\x08\x06\x07\t\x07\x06\x06\x08\x0b\x08\t\n\n\n\n\n\x06\x08\x0b\x0c\x0b\n\x0c\t\n\n\n\xff\xdb\x00C\x01\x02\x02\x02\x02\x02\x02\x05\x03\x03\x05\n\x07\x06\x07\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\xff\xc0\x00\x11\x08\x01\xe0\x02\x80\x03\x01"\x00\x02\x11\x01\x03\x11\x01\xff\xc4\x00\x1f\x00\x00\x01\x05\x01\x01\x01\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x01\x02\x03\x04\x05\x06\x07\x08\t\n\x0b\xff\xc4\x00\xb5\x10\x00\x02\x01\x03\x03\x02\x04\x03\x05\x05\x04\x04\x00\x00\x01}\x01\x02\x03\x00\x04\x11\x05\x12!1A\x06\x13Qa\x07"q\x142\x81\x91\xa1\x08#B\xb1\xc1\x15R\xd1\xf0$3br\x82\t\n\x16\x17\x18\x19\x1a%&\'()*456789:CDEFGHIJSTUVWXYZcdefghijstuvwxyz\x83\x84\x85\x86\x87\x88\x89\x8a\x92\x93\x94\x95\x96\

In [19]:
def preprocess(example):
    feature_description = {
        "image" : tf.io.VarLenFeature(tf.string),
        "label" : tf.io.FixedLenFeature([], tf.int64, default_value = 0),
        "xmin" : tf.io.FixedLenFeature([], tf.int64, default_value = 0),
        "ymin" : tf.io.FixedLenFeature([], tf.int64, default_value = 0),
        "xmax" : tf.io.FixedLenFeature([], tf.int64, default_value = 0),
        "ymax" : tf.io.FixedLenFeature([], tf.int64, default_value = 0),    
    }
    
    example_with_image = tf.io.parse_single_example(example, feature_description)
    
    print(example_with_image["image"].values[0])
    decoded_img = tf.io.decode_image(example_with_image["image"].values[0])
    label = example_with_image["label"]
    boundbox = [example_with_image["xmin"]/640, 
                example_with_image["ymin"]/480,
                example_with_image["xmax"]/640,
                example_with_image["ymax"]/480]
    
    """ 
    label_img = example_with_image["label"].numpy()
    decoded_img = cv2.cvtColor(decoded_img.numpy(), cv2.COLOR_BGR2RGB)
    boundbox_img = [example_with_image[edge].numpy() for edge in ["xmin", "ymin", "xmax", "ymax"]]
    copy_img = decoded_img.copy()
    cv2.rectangle(copy_img, (boundbox_img[0], boundbox_img[1]), (boundbox_img[2], boundbox_img[3]), (0,0,0), 2)
    cv2.putText(copy_img,labels[label_img],(boundbox_img[0],boundbox_img[1]), cv2.FONT_HERSHEY_COMPLEX, 1, (0,150,0), 3)
    cv2.imshow("image_{}".format(num),
               copy_img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()"""
    return decoded_img, (label, boundbox)

In [20]:
%matplotlib inline
import matplotlib as mpl
import matplotlib.pyplot as plt


In [21]:
os.listdir(THANKYOU_PATH)
def uniqueFileName(path):
    files = os.listdir(path)
    files_set = set()
    for file in files:
        files_set.add(file[:-4])
    return list(files_set)

In [22]:
uniqueFileName(THANKYOU_PATH)
for file in uniqueFileName(THANKYOU_PATH):
    print(file)

thankyou.de00e415-13b8-11ed-8cee-c025a5433bea
thankyou.e06c599c-13b8-11ed-b599-c025a5433bea
thankyou.e1a2ecaa-13b8-11ed-9581-c025a5433bea
thankyou.df3566ef-13b8-11ed-a5f1-c025a5433bea
thankyou.e2d86d3a-13b8-11ed-8024-c025a5433bea


In [23]:
def folderToFile(path, name):
    serialized_examples = []
    for file_name in uniqueFileName(path):
        print(file_name)
        example_image = createExample(os.path.join(path, file_name + ".jpg"), os.path.join(path, file_name + ".xml"))
        serialized_examples.append(example_image.SerializeToString())
    with tf.io.TFRecordWriter("{}_example.tfrecord".format(name)) as f:
        for serialized_example in serialized_examples:
            f.write(serialized_example)
            time.sleep(1)

In [24]:
folderToFile(THANKYOU_PATH, name = "thankyou")

thankyou.de00e415-13b8-11ed-8cee-c025a5433bea
tf.Tensor(b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01\x01,\x01,\x00\x00\xff\xdb\x00C\x00\x02\x01\x01\x01\x01\x01\x02\x01\x01\x01\x02\x02\x02\x02\x02\x04\x03\x02\x02\x02\x02\x05\x04\x04\x03\x04\x06\x05\x06\x06\x06\x05\x06\x06\x06\x07\t\x08\x06\x07\t\x07\x06\x06\x08\x0b\x08\t\n\n\n\n\n\x06\x08\x0b\x0c\x0b\n\x0c\t\n\n\n\xff\xdb\x00C\x01\x02\x02\x02\x02\x02\x02\x05\x03\x03\x05\n\x07\x06\x07\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\xff\xc0\x00\x11\x08\x01\xe0\x02\x80\x03\x01"\x00\x02\x11\x01\x03\x11\x01\xff\xc4\x00\x1f\x00\x00\x01\x05\x01\x01\x01\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x01\x02\x03\x04\x05\x06\x07\x08\t\n\x0b\xff\xc4\x00\xb5\x10\x00\x02\x01\x03\x03\x02\x04\x03\x05\x05\x04\x04\x00\x00\x01}\x01\x02\x03\x00\x04\x11\x05\x12!1A\x06\x13Qa\x07"q\x142\x81\x91\xa1\x08#B\xb1\xc1\x15R\xd1\xf0$3br\x82\t\n\x16\x17\x18\x19\x1a%&\'()*456789:CDEFGHIJSTUVWXYZcdefghijstuvwxyz\x83\x8

In [26]:
def to_image_dataset(filepaths, n_read_threads = 5, shuffle_buffer_size = None, 
                    n_parse_threads = 5, batch_size = 32, cache = True, repeat = False):
    dataset = tf.data.TFRecordDataset(filepaths, num_parallel_reads = n_read_threads)
    
    if cache:
        dataset = dataset.cache()
    if shuffle_buffer_size:
        dataset = dataset.shuffle(shuffle_buffer_size)
    if repeat:
        dataset = dataset.repeat()
    
    dataset = dataset.map(preprocess, num_parallel_calls=n_parse_threads)
    dataset = dataset.batch(batch_size)
    return dataset.prefetch(1)
        

In [27]:
dataset_t =  to_image_dataset("example.tfrecord")

Tensor("strided_slice:0", shape=(), dtype=string)


In [28]:
for X, (y1, y2) in dataset_t.take(1):
    for i in range(5):
        cv2.imshow("hello",X[i].numpy())
        cv2.waitKey(0)
        cv2.destroyAllWindows()
        print(y1[i] , y2[i])

tf.Tensor(2, shape=(), dtype=int64) tf.Tensor([0.0015625 0.2875    0.7265625 0.95     ], shape=(4,), dtype=float64)
tf.Tensor(2, shape=(), dtype=int64) tf.Tensor([0.0015625 0.475     0.884375  1.       ], shape=(4,), dtype=float64)
tf.Tensor(2, shape=(), dtype=int64) tf.Tensor([0.0015625  0.21666667 0.63125    0.93541667], shape=(4,), dtype=float64)
tf.Tensor(2, shape=(), dtype=int64) tf.Tensor([0.0015625  0.37083333 0.821875   1.        ], shape=(4,), dtype=float64)
tf.Tensor(2, shape=(), dtype=int64) tf.Tensor([0.0046875  0.21666667 0.6109375  0.91666667], shape=(4,), dtype=float64)


In [29]:
TRAIN_PATH = os.path.join("workspace","images","train")
folderToFile(TRAIN_PATH,name = "train")

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [30]:
train_set = to_image_dataset("train_example.tfrecord", batch_size = 16, repeat = True)

Tensor("strided_slice:0", shape=(), dtype=string)


In [31]:
for X, (y_label, y_box) in train_set.take(1):
    for i in range(10):
        label = y_label[i].numpy()
        cv2.imshow("hello_{}".format(labels[label]),X[i].numpy())
        print(y_box[i], y_label[i])
        cv2.waitKey(0)
        cv2.destroyAllWindows()
        

tf.Tensor([0.1203125  0.19791667 0.5828125  1.        ], shape=(4,), dtype=float64) tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor([0.0015625  0.21666667 0.63125    0.93541667], shape=(4,), dtype=float64) tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor([0.1953125  0.00833333 0.6515625  0.82708333], shape=(4,), dtype=float64) tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor([0.0015625 0.475     0.884375  1.       ], shape=(4,), dtype=float64) tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor([0.1390625 0.00625   0.565625  0.825    ], shape=(4,), dtype=float64) tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor([0.0015625  0.15208333 0.509375   0.99375   ], shape=(4,), dtype=float64) tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor([0.1015625  0.0125     0.546875   0.91041667], shape=(4,), dtype=float64) tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor([0.2078125 0.48125   0.503125  1.       ], shape=(4,), dtype=float64) tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor([0.1484375  0.30833333 0.509375   0.977083

In [32]:
folderToFile(TEST_PATH, "test")

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [33]:
test_set = to_image_dataset("test_example.tfrecord")

Tensor("strided_slice:0", shape=(), dtype=string)


In [33]:
# class ResidentialUnit(tf.keras.layers.Layer):
#     def __init__(self, filters, strides = 1, activation = "relu", **kargs):
#         super().__init__(**kargs)
#         self.activation = tf.keras.activations.get(activation)
#         self.main_layers = [
#             DefaultConv2D(filters, strides = strides),
#             tf.keras.layers.BatchNormalization(),
#             self.activation,
#             DefaultConv2D(filters),
#             tf.keras.layers.BatchNormalization()
#         ]
#         self.skip_layers = []
#         if strides > 1:
#             self.skip_layers = [
#                 DefaultConv2D(filters, kernel_size = 1, strides = strides),
#                 tf.keras.layers.BatchNormalization()
#             ]
#     def call(self, inputs):
#         Z = inputs
#         for layer in self.main_layers:
#             Z = layer(Z)
#         skip_Z = inputs
#         for layer in self.skip_layers:
#             skip_Z = layer(skip_Z)
#         return self.activation(Z + skip_Z)
    
#     def get_config(self):
#         config = super().get_config()
#         return {**config, 
#                "main_layer" : [keras.layers.serialize(layer) for layer in self.main_layers],
#                "skip_layer" : [keras.layers.serialize(layer) for layer in self.skip_layers],
#                "activation" : keras.activations.serialize(self.activation)}

In [34]:
"""from functools import partial 
from tensorflow import keras
DefaultConv2D = partial(tf.keras.layers.Conv2D, kernel_size = 3, strides = 1, padding = "SAME", use_bias = False)

model = tf.keras.models.Sequential()
model.add(DefaultConv2D(64, kernel_size = 7, strides = 2, input_shape = [480,640,3], padding = "SAME"))
model.add(tf.keras.layers.BatchNormalization())
model.add(tf.keras.layers.Activation("relu"))

prev_filters = 64
for filters in [64]*3 + [128]*3 + [256]*3:
    strides = 1 if filters == prev_filters else 2
    model.add(ResidentialUnit(filters, strides = strides))
    prev_filters = filters

model.add(tf.keras.layers.MaxPool2D(pool_size = 3, strides = 2, padding = "SAME"))
model.add(tf.keras.layers.GlobalAvgPool2D())
model.add(tf.keras.layers.Flatten())
model.add(keras.layers.Dropout(rate = 0.4))
model.add(tf.keras.layers.Dense(200, activation = "relu"))
model.add(keras.layers.Dropout(rate = 0.4))
model.add(keras.layers.Dense(7, activation = "softmax"))"""

'from functools import partial \nfrom tensorflow import keras\nDefaultConv2D = partial(tf.keras.layers.Conv2D, kernel_size = 3, strides = 1, padding = "SAME", use_bias = False)\n\nmodel = tf.keras.models.Sequential()\nmodel.add(DefaultConv2D(64, kernel_size = 7, strides = 2, input_shape = [480,640,3], padding = "SAME"))\nmodel.add(tf.keras.layers.BatchNormalization())\nmodel.add(tf.keras.layers.Activation("relu"))\n\nprev_filters = 64\nfor filters in [64]*3 + [128]*3 + [256]*3:\n    strides = 1 if filters == prev_filters else 2\n    model.add(ResidentialUnit(filters, strides = strides))\n    prev_filters = filters\n\nmodel.add(tf.keras.layers.MaxPool2D(pool_size = 3, strides = 2, padding = "SAME"))\nmodel.add(tf.keras.layers.GlobalAvgPool2D())\nmodel.add(tf.keras.layers.Flatten())\nmodel.add(keras.layers.Dropout(rate = 0.4))\nmodel.add(tf.keras.layers.Dense(200, activation = "relu"))\nmodel.add(keras.layers.Dropout(rate = 0.4))\nmodel.add(keras.layers.Dense(7, activation = "softmax"))'

In [35]:
# model.compile(loss = "sparse_categorical_crossentropy", optimizer = "nadam", metrics = ["accuracy"])

In [36]:
# model.summary()

In [34]:
from tensorflow import keras

early_stopping_cb = tf.keras.callbacks.EarlyStopping(patience = 10, restore_best_weights = True)
checkpoint_cb = keras.callbacks.ModelCheckpoint("fec_model_basic_xception.h5")
model.fit(train_set,steps_per_epoch = 28821//32, epochs = 5)

NameError: name 'model' is not defined

In [35]:
keras.backend.clear_session()

In [36]:
model.summary()

NameError: name 'model' is not defined

In [37]:
optimizer = keras.optimizers.SGD(learning_rate=0.2, momentum=0.9, decay=0.01)

base_model = keras.applications.xception.Xception(weights = "imagenet",
                                                 include_top = False)
avg = keras.layers.GlobalAveragePooling2D()(base_model.output)
class_output = keras.layers.Dense(4, activation = "softmax")(avg)
loc_output = keras.layers.Dense(4, activation = "relu")(avg)
model = keras.models.Model(inputs = base_model.input,
                          outputs = [class_output, loc_output])


for layer in base_model.layers:
    layer.trainable = False

model.compile(loss = ["sparse_categorical_crossentropy", "mse"],
             loss_weights = [0.95, 0.05], 
             optimizer = optimizer,
             metrics = ["accuracy"])

In [38]:
model.fit(train_set,steps_per_epoch = 10, epochs = 5)

Epoch 1/5
10/10 [==============================] - 12s 548ms/step - loss: 54569.0742 - dense_loss: 57441.0195 - dense_1_loss: 2.1785 - dense_accuracy: 0.2562 - dense_1_accuracy: 0.1000
Epoch 2/5
10/10 [==============================] - 5s 549ms/step - loss: 52108.8828 - dense_loss: 54851.4297 - dense_1_loss: 0.3532 - dense_accuracy: 0.3875 - dense_1_accuracy: 0.0000e+00
Epoch 3/5
10/10 [==============================] - 6s 550ms/step - loss: 9841.4902 - dense_loss: 10359.4453 - dense_1_loss: 0.3534 - dense_accuracy: 0.6000 - dense_1_accuracy: 0.0000e+00
Epoch 4/5
10/10 [==============================] - 6s 551ms/step - loss: 2139.5210 - dense_loss: 2252.1089 - dense_1_loss: 0.3534 - dense_accuracy: 0.7437 - dense_1_accuracy: 0.0000e+00
Epoch 5/5
10/10 [==============================] - 6s 552ms/step - loss: 764.8752 - dense_loss: 805.1132 - dense_1_loss: 0.3545 - dense_accuracy: 0.8938 - dense_1_accuracy: 0.0000e+00


In [42]:
for layer in base_model.layers:
    layer.trainable = True

model.compile(loss = ["sparse_categorical_crossentropy", "mse"],
             loss_weights = [0.8, 0.2], 
             optimizer = optimizer,
             metrics = ["accuracy"])

In [43]:
model.fit(train_set, steps_per_epoch = 10, epochs =5)

Epoch 1/5


ResourceExhaustedError: Graph execution error:

Detected at node 'model/block2_sepconv1/separable_conv2d' defined at (most recent call last):
    File "C:\Users\Dell\miniconda3\envs\tf2\lib\runpy.py", line 194, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "C:\Users\Dell\miniconda3\envs\tf2\lib\runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "C:\Users\Dell\miniconda3\envs\tf2\lib\site-packages\ipykernel_launcher.py", line 17, in <module>
      app.launch_new_instance()
    File "C:\Users\Dell\miniconda3\envs\tf2\lib\site-packages\traitlets\config\application.py", line 976, in launch_instance
      app.start()
    File "C:\Users\Dell\miniconda3\envs\tf2\lib\site-packages\ipykernel\kernelapp.py", line 712, in start
      self.io_loop.start()
    File "C:\Users\Dell\miniconda3\envs\tf2\lib\site-packages\tornado\platform\asyncio.py", line 215, in start
      self.asyncio_loop.run_forever()
    File "C:\Users\Dell\miniconda3\envs\tf2\lib\asyncio\base_events.py", line 570, in run_forever
      self._run_once()
    File "C:\Users\Dell\miniconda3\envs\tf2\lib\asyncio\base_events.py", line 1859, in _run_once
      handle._run()
    File "C:\Users\Dell\miniconda3\envs\tf2\lib\asyncio\events.py", line 81, in _run
      self._context.run(self._callback, *self._args)
    File "C:\Users\Dell\miniconda3\envs\tf2\lib\site-packages\ipykernel\kernelbase.py", line 510, in dispatch_queue
      await self.process_one()
    File "C:\Users\Dell\miniconda3\envs\tf2\lib\site-packages\ipykernel\kernelbase.py", line 499, in process_one
      await dispatch(*args)
    File "C:\Users\Dell\miniconda3\envs\tf2\lib\site-packages\ipykernel\kernelbase.py", line 406, in dispatch_shell
      await result
    File "C:\Users\Dell\miniconda3\envs\tf2\lib\site-packages\ipykernel\kernelbase.py", line 730, in execute_request
      reply_content = await reply_content
    File "C:\Users\Dell\miniconda3\envs\tf2\lib\site-packages\ipykernel\ipkernel.py", line 390, in do_execute
      res = shell.run_cell(code, store_history=store_history, silent=silent)
    File "C:\Users\Dell\miniconda3\envs\tf2\lib\site-packages\ipykernel\zmqshell.py", line 528, in run_cell
      return super().run_cell(*args, **kwargs)
    File "C:\Users\Dell\miniconda3\envs\tf2\lib\site-packages\IPython\core\interactiveshell.py", line 2901, in run_cell
      result = self._run_cell(
    File "C:\Users\Dell\miniconda3\envs\tf2\lib\site-packages\IPython\core\interactiveshell.py", line 2947, in _run_cell
      return runner(coro)
    File "C:\Users\Dell\miniconda3\envs\tf2\lib\site-packages\IPython\core\async_helpers.py", line 68, in _pseudo_sync_runner
      coro.send(None)
    File "C:\Users\Dell\miniconda3\envs\tf2\lib\site-packages\IPython\core\interactiveshell.py", line 3172, in run_cell_async
      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
    File "C:\Users\Dell\miniconda3\envs\tf2\lib\site-packages\IPython\core\interactiveshell.py", line 3364, in run_ast_nodes
      if (await self.run_code(code, result,  async_=asy)):
    File "C:\Users\Dell\miniconda3\envs\tf2\lib\site-packages\IPython\core\interactiveshell.py", line 3444, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "C:\Users\Dell\AppData\Local\Temp\ipykernel_28352\2499136918.py", line 1, in <module>
      model.fit(train_set, steps_per_epoch = 10, epochs =5)
    File "C:\Users\Dell\miniconda3\envs\tf2\lib\site-packages\keras\utils\traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\Dell\miniconda3\envs\tf2\lib\site-packages\keras\engine\training.py", line 1409, in fit
      tmp_logs = self.train_function(iterator)
    File "C:\Users\Dell\miniconda3\envs\tf2\lib\site-packages\keras\engine\training.py", line 1051, in train_function
      return step_function(self, iterator)
    File "C:\Users\Dell\miniconda3\envs\tf2\lib\site-packages\keras\engine\training.py", line 1040, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\Dell\miniconda3\envs\tf2\lib\site-packages\keras\engine\training.py", line 1030, in run_step
      outputs = model.train_step(data)
    File "C:\Users\Dell\miniconda3\envs\tf2\lib\site-packages\keras\engine\training.py", line 889, in train_step
      y_pred = self(x, training=True)
    File "C:\Users\Dell\miniconda3\envs\tf2\lib\site-packages\keras\utils\traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\Dell\miniconda3\envs\tf2\lib\site-packages\keras\engine\training.py", line 490, in __call__
      return super().__call__(*args, **kwargs)
    File "C:\Users\Dell\miniconda3\envs\tf2\lib\site-packages\keras\utils\traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\Dell\miniconda3\envs\tf2\lib\site-packages\keras\engine\base_layer.py", line 1014, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "C:\Users\Dell\miniconda3\envs\tf2\lib\site-packages\keras\utils\traceback_utils.py", line 92, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\Dell\miniconda3\envs\tf2\lib\site-packages\keras\engine\functional.py", line 458, in call
      return self._run_internal_graph(
    File "C:\Users\Dell\miniconda3\envs\tf2\lib\site-packages\keras\engine\functional.py", line 596, in _run_internal_graph
      outputs = node.layer(*args, **kwargs)
    File "C:\Users\Dell\miniconda3\envs\tf2\lib\site-packages\keras\utils\traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\Dell\miniconda3\envs\tf2\lib\site-packages\keras\engine\base_layer.py", line 1014, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "C:\Users\Dell\miniconda3\envs\tf2\lib\site-packages\keras\utils\traceback_utils.py", line 92, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\Dell\miniconda3\envs\tf2\lib\site-packages\keras\layers\convolutional\separable_conv2d.py", line 180, in call
      outputs = tf.compat.v1.nn.separable_conv2d(
Node: 'model/block2_sepconv1/separable_conv2d'
OOM when allocating tensor with shape[16,128,237,317] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node model/block2_sepconv1/separable_conv2d}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.
 [Op:__inference_train_function_16910]

In [39]:
model.evaluate(test_set, steps = 1)

1/1 [==============================] - 4s 4s/step - loss: 0.0177 - dense_loss: 0.0000e+00 - dense_1_loss: 0.3539 - dense_accuracy: 1.0000 - dense_1_accuracy: 0.0000e+00


[0.017693104222416878, 0.0, 0.35386207699775696, 1.0, 0.0]

In [40]:
y_pred = model.predict(test_set, steps = 1)

1/1 [==============================] - 1s 577ms/step


In [41]:
y_pred

[array([[0., 0., 0., 1.],
        [0., 0., 1., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 1., 0., 0.],
        [0., 0., 0., 1.],
        [0., 1., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [0., 0., 0., 1.],
        [1., 0., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 1., 0., 0.],
        [1., 0., 0., 0.],
        [0., 0., 1., 0.]], dtype=float32),
 array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=float32)]